# Generated by Django 4.0 on 2023-02-01 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.ImageField(upload_to="upload/%Y/%m/%d/")),
                ("uploaded", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
