# Generated by Django 4.0 on 2023-01-01 01:06

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="New category", max_length=200)),
                ("slug", models.SlugField(max_length=200)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="blog.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="Untitled post", max_length=200)),
                ("slug", models.SlugField(max_length=200)),
                ("excerpt", models.CharField(blank=True, max_length=200, null=True)),
                ("content", models.TextField(blank=True, null=True)),
                (
                    "fig",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="",
                        verbose_name="feature photo of post",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        default=datetime.datetime(2023, 1, 1, 8, 6, 53, 637974)
                    ),
                ),
                (
                    "edited_date",
                    models.DateTimeField(
                        default=datetime.datetime(2023, 1, 1, 8, 6, 53, 637986)
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="post_in_cate",
                        to="blog.category",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="auth.user"
                    ),
                ),
            ],
        ),
    ]
