# Generated by HaiTruong DFI on 2023-01-01 01:07
# This is migration for creating first default category of app

from django.db import migrations


def create_first_default_category(apps, schema_editor):
    Category = apps.get_model("blog", "Category")
    c = Category(name="Uncategorized", parent=None, slug="uncategorized")
    c.save()


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_first_default_category),
    ]
