# Generated by Django 4.0 on 2023-01-04 03:39

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_auto_20230101_0807"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="blog.category",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="posts_in_category",
                to="blog.category",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="created_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 1, 4, 10, 39, 43, 179194)
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="edited_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 1, 4, 10, 39, 43, 179205)
            ),
        ),
    ]
