# Generated by Django 4.0 on 2023-01-04 02:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20230101_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='posts_in_category', to='blog.category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 4, 9, 51, 57, 762961)),
        ),
        migrations.AlterField(
            model_name='post',
            name='edited_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 4, 9, 51, 57, 762972)),
        ),
    ]
