# Generated by Django 4.0 on 2022-12-30 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(primary_key=True, serialize=False, unique=True),
                ),
                ("avatar", models.ImageField(blank=True, null=True, upload_to="")),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="userprofile",
                        to="auth.user",
                    ),
                ),
            ],
        ),
    ]
